### ISSUE TITLE
Use together with ufront nodejs target

### ISSUE THREAD

**Issue by varadig** [kevinresol/hxgenjs#2]
I need to use hxgenjs with ufront (and some other lib) nodejs target.

build.hxml:
```
genjs.hxml

-lib hxgenjs

--macro allowPackage("sys")
-lib ufront-mvc
-lib hxnodejs
-lib js-kit
-lib smtpmailer
-lib record-macros
-lib gotocorehaxe
-lib gotocorehxnode
-lib erazor
-lib haxe-crypto
-lib hxnodejs-jsonwebtoken
-lib express
-lib tink_streams
-lib dotenv
-lib exceljs-hx
-js genjs/www/index.js
-dce full

```

genjs.hxml:
```
-cp src
-main Server

```
```

haxe build.hxml

src/model/api/AuthApi.hx:128: characters 63-67 : Unknown identifier : auth
src/model/api/AuthApi.hx:128: characters 63-67 : For function argument 'value'
/Volumes/Work/Haxe/libs/ufront-mvc/git/src/ufront/api/UFAsyncApi.hx:95: characters 2-67 : Missing return: tink.Surprise<_makeApiCall.A, tink.TypedError<ufront.remoting.RemotingError<_makeApiCall.B>>>
/Volumes/Work/Haxe/libs/ufront-mvc/git/src/ufront/web/result/CallJavascriptResult.hx:99: characters 16-24 : Unknown identifier : document
/Volumes/Work/Haxe/libs/ufront-mvc/git/src/ufront/web/result/CallJavascriptResult.hx:106: characters 17-25 : Unknown identifier : document
/Volumes/Work/Haxe/libs/ufront-mvc/git/src/ufront/web/result/CallJavascriptResult.hx:112: characters 4-12 : Unknown identifier : document
/Volumes/Work/Haxe/libs/ufront-mvc/git/src/ufront/web/result/CallJavascriptResult.hx:113: characters 4-12 : Unknown identifier : document
```

**Comment by varadig** [comment]
Ok I think, solved this too :)
I forgot to add this compiler definition

-D server

**Comment by varadig** [comment]
Ok, now everything is compiled, but when I wanted to run node index.js I got this:

ReferenceError: $hxClasses is not defined
    at Object.<anonymous> (/Volumes/Work/Haxe/besocial/otponkentesseg/genjs/www/Std.js:25:31)

**Comment by varadig** [comment]
The Std.js line 25:

`	String.prototype.__class__ = $hxClasses["String"] = String`

**Comment by varadig** [comment]
Ok I'm pretty shure the problem is with the ufront-mvc
If I add -D server flag:
`ReferenceError: $hxClasses is not defined`

Here is a minimal sample project:
[hxgenjs.zip](https://github.com/kevinresol/hxgenjs/files/1274838/hxgenjs.zip)

**Comment by varadig** [comment]
Hi @kevinresol, thanks for the fix, but now i got this:

```
/Volumes/Work/Haxe/hxgenjs/www/minject/Injector.js:233
        throw new (js__$Boot_HaxeError().default)("Could not determine type name of " + (Std().default).string(value));
        ^
Error: Could not determine type name of {
        __name__ : [ufront,app,DefaultUfrontController], 
        __meta__ : {
                fields : {
                        showMessage : {
                                wrapResult : [<...>]
                        }
                }
        }
}
    at Function.Injector.getValueType (/Volumes/Work/Haxe/hxgenjs/www/minject/Injector.js:233:8)
    at Object.mapRuntimeTypeOf (/Volumes/Work/Haxe/hxgenjs/www/minject/Injector.js:39:32)
    at Object.UfrontApplication [as __class__] (/Volumes/Work/Haxe/hxgenjs/www/ufront/app/UfrontApplication.js:67:17)
    at Function.Main.main (/Volumes/Work/Haxe/hxgenjs/www/Main.js:35:14)
    at Object.<anonymous> (/Volumes/Work/Haxe/hxgenjs/www/server.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by kevinresol** [comment]
Can you try 0.2.4?

**Comment by varadig** [comment]
Yes, now I can run the node UFrontApp, but I got this error:

```
[GET /] from [::1 The Boss], response: [500 text/html]
  Log: ufront.app.HttpApplication.executeModules(422): Caught error TypeError: Cannot read property 'actionContext' of undefined while executing module ufront.web.MVCHandler.handleRequest in HttpApplication.executeModules()
  Error: ufront.web.ErrorPageHandler.handleError(44): Handling error: Error#500: Internal Server Error @ ufront.web.MVCHandler.handleRequest:-1 (TypeError: Cannot read property 'actionContext' of undefined)

```
I made two hxml (basic.hxml && hxgen.hxml). The basic.hxml does not throw error.

[hxgenjs.zip](https://github.com/kevinresol/hxgenjs/files/1276010/hxgenjs.zip)

**Comment by kevinresol** [comment]
This is harder to fix then I expected. Mostly because ufront is too complex in terms of its structure and it tends to reports error positions incorrectly. So my advice for now is, don't use ufront with hxgenjs.

So you can either use ufront alone, without hxgenjs.
Or if you really need hxgenjs you can consider try using other web frameworks such as tink_web.

Btw, may I know why you want to split a server app into individual js files?

**Comment by varadig** [comment]
I wanted to split the code, because there is a lot of update on server side, and I don't wanted to upload/update any part.

**Comment by kevinresol** [comment]
if you could locate the actual line of js code where the error `Cannot read property 'actionContext' of undefined` occurs, it would be good...

**Comment by varadig** [comment]
In the HomeController.js, execute method:
```
...
	execute: function() {
		console.log("context:"+this.context);//context:undefined
...

```

```
// Class: HomeController

var $global = typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this

$global.Object.defineProperty(exports, "__esModule", {value: true});

var __map_reserved = {};

// Imports

var $hxClasses = require("./hxClasses_stub").default;
var $import = require("./import_stub").default;
var $extend = require("./extend_stub").default;
function ufront_web_Controller() {return require("./ufront/web/Controller");}
function ufront_web_result_ViewResult() {return require("./ufront/web/result/ViewResult");}
function ufront_view__$TemplateData_TemplateData_$Impl_$() {return require("./ufront/view/_TemplateData/TemplateData_Impl_");}
function haxe_rtti_Meta() {return require("./haxe/rtti/Meta");}
function js__$Boot_HaxeError() {return require("./js/_Boot/HaxeError");}
function ufront_web_HttpError() {return require("./ufront/web/HttpError");}
function ufront_core_SurpriseTools() {return require("./ufront/core/SurpriseTools");}
function Std() {return require("./Std");}

// Constructor

var HomeController = function() {
	(ufront_web_Controller().default).call(this);
}

// Meta

HomeController.__name__ = ["HomeController"];
HomeController.__super__ = ufront_web_Controller;
HomeController.prototype = $extend((ufront_web_Controller().default).prototype, {
	index: function() {
		var obj = { };
		var this1 = obj != null ? obj : { };
		return new (ufront_web_result_ViewResult().default)((ufront_view__$TemplateData_TemplateData_$Impl_$().default).setObject(this1,{ title : "asdasd"}));
	},
	execute: function() {
		console.log("context:"+this.context);//context:undefined
		var uriParts = this.context.actionContext.get_uriParts();
		var params = this.context.request.get_params();
		var method = this.context.request.get_httpMethod();
		this.context.actionContext.controller = this;
		this.context.actionContext.action = "execute";
		try {
			if(method.toLowerCase() == "get" && 0 == uriParts.length) {
				this.context.actionContext.action = "index";
				this.context.actionContext.args = [];
				this.context.actionContext.get_uriParts().splice(0,0);
				var this1 = (haxe_rtti_Meta().default).getFields(HomeController).index.wrapResult[0];
				var wrappingRequired = this1;
				var result = this.wrapResult(this.index(),wrappingRequired);
				this.setContextActionResultWhenFinished(result);
				return result;
			}
			throw new (js__$Boot_HaxeError().default)((ufront_web_HttpError().default).pageNotFound({ fileName : "Main.hx", lineNumber : 19, className : "HomeController", methodName : "execute"}));
		} catch( e ) {
			if (e instanceof (js__$Boot_HaxeError().default)) e = e.val;
			return (ufront_core_SurpriseTools().default).asSurpriseError(e,"Uncaught error while executing " + (Std().default).string(this.context.actionContext.controller) + "." + this.context.actionContext.action + "()",{ fileName : "Main.hx", lineNumber : 19, className : "HomeController", methodName : "execute"});
		}
	}
});
HomeController.prototype.__class__ = $hxClasses["HomeController"] = HomeController;

// Init



// Statics


HomeController.__meta__ = { fields : { index : { wrapResult : [3]}}}

// Export

exports.default = HomeController;
```

**Comment by varadig** [comment]
I think the Controller.js injectContext is not invoked:

```
Controller.prototype = {
	injectContext: function(context) {
		console.log("Controller::injectContext:"+context);

```

**Comment by kevinresol** [comment]
This bug should be fixed by v0.2.5

But you will encounter another bug about view template not found. That is because ufront trying to look for view template files relative to the "script directory" which could be a folder buried down the way for each individual js files.

**Comment by varadig** [comment]
Thanks, the bug is gone!
If I specify viewfolder in UfAppConfig like this:

```
 var ufApp:UfrontApplication = new UfrontApplication({
            indexController:HomeController,
            viewPath:"viewFolder"
        });
        ufApp.listen(8080);
```
![screen shot 2017-09-05 at 11 11 28](https://user-images.githubusercontent.com/6317148/30054031-07db1eda-922b-11e7-8526-e5ed6bc966c6.png)

the ViewEngine not found the viewFolder:

Unable to load view template: Error#500: No template found for home/index with extensions [html,tpl] @ ufront.view.UFViewEngine.getTemplate:165

Or this is a wrong way to setup viewPath?

**Comment by kevinresol** [comment]
as I said, the path is relative to the script directory,
(See source code here: https://github.com/ufront/ufront-mvc/blob/bf4465c/src/ufront/view/FileViewEngine.hx#L55)

and `script directory` is where the running js file resides, which is now inside some folders according to the package structure.

So you can specify it as absolute path, or modify the path resolving logic.

But seems this is no longer issue of this library. Closing for now.

**Comment by varadig** [comment]
Thanks (y)
